# Generated by Django 5.0.6 on 2024-07-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
