# Generated by Django 5.0.6 on 2024-07-03 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_comprador_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprador',
            name='nro_cliente',
        ),
    ]
